spring:
  application:
    name: medical-service
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 60MB
  datasource:
    url: jdbc:mysql://localhost:3306/medical_service?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000

server:
  port: 8081
  servlet:
    context-path: /

# MyBatis-Plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.medical.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# Knife4j
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
knife4j:
  enable: true
  setting:
    language: zh_cn
